/* 
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
var countries={
    "Jordan":{
        id:1,
        ar:"الأردن",
        en:"Jordan",
        timeZone:2,
        countryCode:'JO'
    },
    "Syria":{
        id:2,
        ar:"سوريا",
        en:"Syria",
        timeZone:2,
        countryCode:'SY'
    },
    "Iraq":{
        id:3,
        ar:"العراق",
        en:"Iraq",
        timeZone:3,
        countryCode:'IQ'
    },
    "Palestine":{
        id:4,
        ar:"فلسطين",
        en:"Palestine",
        timeZone:2,
        countryCode:'PS'
    },
    "Lebanon":{
        id:5,
        ar:"لبنان",
        en:"Lebanon",
        timeZone:2,
        countryCode:'LB'
    },
    "Algeria":{
        id:1,
        ar:"الجزائر‎",
        en:"Algeria",
        timeZone:1,
        countryCode:'DZ'
    },
    "Tunisia":{
        id:6,
        ar:"تونس",
        en:"Tunisia",
        timeZone:1,
        countryCode:'TN'
    },
    "Sudan":{
        id:7,
        ar:"السودان",
        en:"Sudan",
        timeZone:3,
        countryCode:'SD'
    },
    "Libya":{
        id:8,
        ar:"ليبيا",
        en:"Libya",
        timeZone:2,
        countryCode:'LY'
    },
    "Egypt":{
        id:9,
        ar:"مصر",
        en:"Egypt",
        timeZone:2,
        countryCode:'EG'
    },
    "Morocco":{
        id:10,
        ar:"المغرب",
        en:"Morocco",
        timeZone:1,
        countryCode:'MA'
    },
    "Mauritania":{
        id:11,
        ar:"موريتانيا",
        en:"Mauritania",
        timeZone:0,
        countryCode:'MR'
    },
    "UAE":{
        id:12,
        ar:"الإمارات",
        en:"UAE",
        timeZone:3,
        countryCode:'AE'
    },
    "Bahrain":{
        id:13,
        ar:"البحرين",
        en:"Bahrain",
        timeZone:3,
        countryCode:'BH'
    },
    "Saudi Arabia":{
        id:14,
        ar:"السعودية",
        en:"Saudi Arabia",
        timeZone:3,
        countryCode:'SA'
    },
    "Oman":{
        id:15,
        ar:"عمان",
        en:"Oman",
        timeZone:4,
        countryCode:'OM'
    },
    "Qatar":{
        id:16,
        ar:"قطر",
        en:"Qatar",
        timeZone:3,
        countryCode:'QA'
    },
    "Kuwait":{
        id:17,
        ar:"الكويت",
        en:"Kuwait",
        timeZone:3,
        countryCode:'KW'
    },
    "Yemen":{
        id:1,
        ar:"اليمن",
        en:"Yemen",
        timeZone:3,
        countryCode:'YE'
    },
    "UTC":{
        id:18,
        ar:"جرينيتش",
        en:"UTC",
        timeZone:0,
        countryCode:'UK'
    }
}

